swagger: '2.0'
info:
  title: OS MCP Server
  description: OS DataHub API MCP Server for Copilot Studio
  version: 1.0.0
host: 127.0.0.1:8000
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /mcp:
    post:
      summary: MCP Server Endpoint
      description: Model Context Protocol server for OS DataHub
      operationId: InvokeMCP
      x-ms-agentic-protocol: mcp-streamable-1.0
      parameters:
        - name: request
          in: body
          required: true
          schema:
            type: object
            required:
              - method
            properties:
              jsonrpc:
                type: string
                default: "2.0"
              id:
                type: string
                default: "1"
              method:
                type: string
                enum:
                  - initialize
                  - tools/list
                  - tools/call
              params:
                type: object
      responses:
        '200':
          description: Success
          schema:
            type: object
securityDefinitions:
  BearerAuth:
    type: apiKey
    name: Authorization
    in: header
security:
  - BearerAuth: []
