#!/usr/bin/env bash
set -euo pipefail

# Simple dev launcher for frontend + readiness checks.
# Usage: ./scripts/dev_frontend.sh [--port 5173] [--mcp-url http://127.0.0.1:8000/mcp] [--token dev-token]
# Requires: npm, jq (optional for pretty output), curl.

PORT=5173
MCP_URL="http://127.0.0.1:8000/mcp"
TOKEN="dev-token"
OPEN_BROWSER=0
EXPECTED_OS_KEY_PREFIX=""

if [[ -n "${OS_API_KEY:-}" ]]; then
  EXPECTED_OS_KEY_PREFIX="${OS_API_KEY:0:6}"
fi

while [[ $# -gt 0 ]]; do
  case "$1" in
    --port) PORT="$2"; shift 2;;
    --mcp-url) MCP_URL="$2"; shift 2;;
    --token) TOKEN="$2"; shift 2;;
    --open) OPEN_BROWSER=1; shift;;
    *) echo "Unknown arg: $1" >&2; exit 1;;
  esac
done

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
FRONTEND_DIR="$ROOT_DIR/frontend"

if [[ ! -d "$FRONTEND_DIR" ]]; then
  echo "[ERROR] frontend directory missing" >&2; exit 1
fi

if ! command -v npm >/dev/null; then
  echo "[ERROR] npm not found on PATH" >&2; exit 1
fi
if ! command -v curl >/dev/null; then
  echo "[ERROR] curl not found on PATH" >&2; exit 1
fi

# Warn if server not reachable
BASE_HOST=$(echo "$MCP_URL" | sed -E 's|/mcp$||')
HEALTH_URL="${BASE_HOST%/}/health"

echo "[INFO] Checking MCP health at $HEALTH_URL ..."
if curl -fsS "$HEALTH_URL" >/dev/null; then
  echo "[INFO] MCP health OK"
else
  echo "[WARN] MCP health check failed. The UI will still start, but tool calls may 401 until server is running." >&2
fi

# Basic auth / token mismatch heuristics
AUTH_DOC=$(curl -fsS "$BASE_HOST/.well-known/mcp-auth" 2>/dev/null || true)
if [[ -n "$AUTH_DOC" ]]; then
  # Try to detect bearer tokens list length if exposed (depends on server exposing metadata; fallback is silent)
  if grep -qi 'bearer' <<<"$AUTH_DOC"; then
    echo "[INFO] MCP auth metadata discovered (.well-known/mcp-auth)"
  fi
fi

if [[ -z "${OS_API_KEY:-}" ]]; then
  echo "[WARN] OS_API_KEY not set in current shell; backend may reject tool calls requiring OS data." >&2
else
  echo "[INFO] OS_API_KEY detected (prefix: ${EXPECTED_OS_KEY_PREFIX}...)"
fi

if [[ -z "${OPENAI_API_KEY:-}" ]]; then
  echo "[INFO] OPENAI_API_KEY not set – chat tool will be unavailable (expected for pure data workflows)."
else
  echo "[INFO] OPENAI_API_KEY present – chat tool should register."
fi

if [[ -n "${BEARER_TOKENS:-}" ]]; then
  # Check if provided TOKEN appears inside BEARER_TOKENS
  if ! grep -q "\b${TOKEN}\b" <(echo "$BEARER_TOKENS" | tr ',' '\n'); then
    echo "[WARN] Provided --token ($TOKEN) not found in BEARER_TOKENS env list; expect 401s unless OS_MCP_AUTH_BYPASS=1." >&2
  else
    echo "[INFO] Token ($TOKEN) found in BEARER_TOKENS list."
  fi
else
  if [[ -z "${OS_MCP_AUTH_BYPASS:-}" ]]; then
    echo "[WARN] BEARER_TOKENS unset and auth bypass not enabled – HTTP server may refuse calls unless legacy fallback in effect." >&2
  else
    echo "[INFO] Auth bypass flag set (OS_MCP_AUTH_BYPASS=$OS_MCP_AUTH_BYPASS)." 
  fi
fi

cd "$FRONTEND_DIR"

if [[ ! -d node_modules ]]; then
  echo "[INFO] Installing frontend dependencies (first run)";
  npm install --no-audit --no-fund
fi

# Create a lightweight env injection file consumed by index.html runtime (window vars)
RUNTIME_JS="public/runtime-config.js"
mkdir -p public
cat > "$RUNTIME_JS" <<EOF
// Generated by dev_frontend.sh
window.MCP_HTTP_URL = "$MCP_URL";
window.MCP_TOKEN = "$TOKEN";
// Optionally override in console if needed.
EOF

echo "[INFO] Wrote runtime config: $RUNTIME_JS"

# Start dev server in background and capture PID
echo "[INFO] Starting Vite dev server on port $PORT ..."
PORT=$PORT npm run dev &
VITE_PID=$!
trap 'echo "[INFO] Stopping dev server (PID $VITE_PID)"; kill $VITE_PID 2>/dev/null || true' EXIT

# Poll for readiness
APP_URL="http://localhost:$PORT"
echo -n "[INFO] Waiting for frontend to become available"
for i in {1..30}; do
  if curl -fsS "$APP_URL" >/dev/null; then
    echo "\n[READY] Frontend running: $APP_URL"
    echo "[INFO] MCP URL: $MCP_URL"
    echo "[INFO] Token: $TOKEN"
    if [[ -n "${OPENAI_API_KEY:-}" ]]; then
      echo "[INFO] Chat tool expected: enabled (OPENAI_API_KEY present)"
    else
      echo "[INFO] Chat tool expected: disabled (no OPENAI_API_KEY)"
    fi
    if [[ $OPEN_BROWSER -eq 1 ]]; then
      if command -v xdg-open >/dev/null; then xdg-open "$APP_URL"; fi
    fi
    wait $VITE_PID
    exit 0
  fi
  echo -n '.'
  sleep 1
done

echo "\n[ERROR] Frontend did not become ready within timeout" >&2
exit 1
